export const translations = {
  ru: {
    extraTurn: 'Дополнительный ход',
    animation: 'Анимация', animationSpeed: 'Скорость анимации', on: 'Вкл', off: 'Выкл',
    resultVictory: 'Победа!', resultDefeat: 'Поражение', playerWins: '{name} победил', computerResigned: 'Компьютер сдался.', youResigned: 'Вы сдались.', playerResigned: '{name} сдался.', ok: 'OK',
    title: 'Калах 1.0', newGame: 'Новая игра', startNewGame: 'Начать новую', mode: 'Режим', pvp: 'Человек против человека', ai: 'Человек против AI', aiName: 'AI', player1: 'Игрок 1', player2: 'Игрок 2', name: 'Имя', difficulty: 'Сложность AI', first: 'Первым ходит', random: 'Случайно', opening: 'Запретить стартовый ход сразу в калах', start: 'Начать игру', save: 'Сохранить', load: 'Загрузить', rules: 'Правила', statistics: 'Статистика', settings: 'Настройки', sound: 'Звук', enableSound: 'Включить звук', volume: 'Громкость', resign: 'Сдаться', resignPlayer: 'Сдаться: {name}', resignConfirm: '{name}: подтвердить сдачу?', pitAria: '{player}: камней в лунке — {count}', boardAria: 'Игровое поле Калах', turn: 'Ходит', kalah1: 'Калах 1', kalah2: 'Калах 2', randomAI: 'Случайный', easy: 'Лёгкий', hard: 'Сложный', advanced: 'Усложнённый', slots: 'Слоты сохранений', empty: 'Пустой слот', overwrite: 'Перезаписать', overwriteConfirm: 'Перезаписать выбранный слот сохранения?', delete: 'Очистить', close: 'Закрыть', totalGames: 'Всего партий', wins: 'Победы', losses: 'Поражения', draws: 'Ничьи', winRate: 'Процент побед', history: 'История', noHistory: 'Истории пока нет', difficultyStats: 'По сложности AI', helpText: 'В Калахе 12 обычных лунок — по 6 у каждого игрока — и два калаха, по одному у каждой стороны. В начале в каждой обычной лунке лежит по 6 камней, всего 72. Игрок выбирает непустую лунку своей стороны и раскладывает камни против часовой стрелки; калах соперника всегда пропускается. Последний камень в своём калахе даёт дополнительный ход. Последний камень в пустой собственной лунке забирает её камень и все камни противоположной лунки в свой калах. Игра заканчивается, когда все обычные лунки одной стороны пусты: оставшиеся камни другой стороны собираются в её калах. Игрок может сдаться; в остальных случаях побеждает тот, у кого больше камней в калахе, а равный счёт означает ничью. Опциональный запрет стартового хода действует только на фактического первого игрока и только до первого успешного посева: нельзя выбрать ход, сразу завершающийся в собственном калахе. Само достижение 37 или более камней игру не завершает.', gameOver: 'Партия завершена', winner: 'Победитель', draw: 'Ничья', endEmptySide: 'пустая сторона', endResign: 'сдача', saved: 'Сохранено', loaded: 'Загружено', activeGame: 'Есть активная партия. Начать новую?', cancel: 'Отмена', confirm: 'Подтвердить', language: 'Язык', moves: 'Ходы', captures: 'Захваты', capturedStones: 'Камни захвата', storeFinishes: 'Финиши в калахе', maxCapture: 'Макс. захват', maxExtra: 'Макс. серия доп. ходов', avgMoves: 'Средние ходы', avgCaptures: 'Средние захваты', avgCaptured: 'Средние камни захвата', avgStore: 'Средние финиши в калахе'
  },
  en: {
    extraTurn: 'Extra turn',
    animation: 'Animation', animationSpeed: 'Animation speed', on: 'On', off: 'Off',
    resultVictory: 'Victory!', resultDefeat: 'Defeat', playerWins: '{name} wins', computerResigned: 'Computer resigned.', youResigned: 'You resigned.', playerResigned: '{name} resigned.', ok: 'OK',
    title: 'Kalah 1.0', newGame: 'New game', startNewGame: 'Start new game', mode: 'Mode', pvp: 'Human vs human', ai: 'Human vs AI', aiName: 'AI', player1: 'Player 1', player2: 'Player 2', name: 'Name', difficulty: 'AI difficulty', first: 'First player', random: 'Random', opening: 'Disallow opening move directly into Kalah', start: 'Start game', save: 'Save', load: 'Load', rules: 'Rules', statistics: 'Statistics', settings: 'Settings', sound: 'Sound', enableSound: 'Enable sound', volume: 'Volume', resign: 'Resign', resignPlayer: 'Resign: {name}', resignConfirm: '{name}: confirm resignation?', pitAria: '{player}: stones in pit — {count}', boardAria: 'Kalah board', turn: 'Turn', kalah1: 'Kalah 1', kalah2: 'Kalah 2', randomAI: 'Random', easy: 'Easy', hard: 'Hard', advanced: 'Advanced', slots: 'Save slots', empty: 'Empty slot', overwrite: 'Overwrite', overwriteConfirm: 'Overwrite the selected save slot?', delete: 'Clear', close: 'Close', totalGames: 'Total games', wins: 'Wins', losses: 'Losses', draws: 'Draws', winRate: 'Win rate', history: 'History', noHistory: 'No games yet', difficultyStats: 'By AI difficulty', helpText: 'Kalah has 12 ordinary pits — 6 belonging to each player — and two Kalah stores, one per side. Each ordinary pit starts with 6 stones, for 72 stones in total. Choose a non-empty pit on your side and sow counter-clockwise; the opponent’s Kalah is always skipped. A final stone in your own Kalah grants an extra turn. A final stone in an empty own pit captures that stone and all stones in the opposite pit into your Kalah. The game ends when all ordinary pits on either side are empty; all remaining stones on the other side are collected into that side’s Kalah. A player may resign; otherwise the larger Kalah score wins and an equal score is a draw. The optional opening restriction applies only to the actual starting player until the first successful sow: the move that would finish directly in that player’s Kalah is unavailable. Reaching 37 or more stones alone does not end the game.', gameOver: 'Game over', winner: 'Winner', draw: 'Draw', endEmptySide: 'empty side', endResign: 'resignation', saved: 'Saved', loaded: 'Loaded', activeGame: 'An active game exists. Start a new one?', cancel: 'Cancel', confirm: 'Confirm', language: 'Language', moves: 'Moves', captures: 'Captures', capturedStones: 'Captured stones', storeFinishes: 'Store finishes', maxCapture: 'Max capture', maxExtra: 'Max extra-turn streak', avgMoves: 'Average moves', avgCaptures: 'Average captures', avgCaptured: 'Average captured stones', avgStore: 'Average store finishes'
  }
};
