import test from 'node:test'; import assert from 'node:assert/strict';
import { KalahGame, TOTAL_STONES, createInitialBoard } from '../js/core/game.js';
const sum = (b) => b.reduce((a, n) => a + n, 0);
const custom = (entries, currentPlayer = 1) => { const board = Array(14).fill(0); for (const [i, n] of entries) board[i] = n; const used = sum(board); board[currentPlayer === 1 ? 6 : 13] += TOTAL_STONES - used; return new KalahGame({ board, currentPlayer, startingPlayer: currentPlayer, firstMoveCompleted: true }); };

test('initial board has 14 entries and exactly 72 stones', () => { const game = new KalahGame(); assert.deepEqual(game.board, createInitialBoard()); assert.equal(sum(game.board), 72); });
test('each player receives their own six legal non-empty pits', () => { const game = new KalahGame(); assert.deepEqual(game.getLegalMoves(), [0,1,2,3,4,5]); game.currentPlayer = 2; assert.deepEqual(game.getLegalMoves(), [7,8,9,10,11,12]); });
test('rejects opponent pits, stores, empty pits and moves after game over', () => { const game = new KalahGame(); assert.equal(game.makeMove(7).reason, 'NOT_OWN_PIT'); assert.equal(game.makeMove(6).reason, 'NOT_OWN_PIT'); game.board[0] = 0; game.board[6] += 6; assert.equal(game.makeMove(0).reason, 'EMPTY_PIT'); game.resign(1); assert.equal(game.makeMove(1).reason, 'GAME_OVER'); });
test('normal sowing switches player and preserves invariant', () => { const game = new KalahGame(); const result = game.makeMove(1); assert.equal(result.success, true); assert.equal(result.extraTurn, false); assert.equal(game.currentPlayer, 2); assert.equal(sum(game.board), 72); });
test('player one and player two skip the opposing Kalah', () => { let game = custom([[0,1],[5,20],[7,1]]); game.makeMove(5); assert.equal(game.board[13], 0); game = custom([[0,1],[7,20],[12,1]], 2); game.makeMove(7); assert.equal(game.board[6], 0); });
test('both players get an extra turn when ending in their own store', () => { let game = new KalahGame(); let result = game.makeMove(0); assert.equal(result.extraTurn, true); assert.equal(game.currentPlayer, 1); game = new KalahGame({ currentPlayer: 2, startingPlayer: 2 }); result = game.makeMove(7); assert.equal(result.extraTurn, true); assert.equal(game.currentPlayer, 2); });
test('captures for player one and player two move both pits to store', () => { let game = custom([[2,1],[9,4]]); let result = game.makeMove(2); assert.equal(result.capturedStones, 5); assert.equal(game.board[3], 0); assert.equal(game.board[9], 0); game = custom([[1,4],[10,1]], 2); result = game.makeMove(10); assert.equal(result.capturedStones, 5); assert.equal(game.board[11], 0); assert.equal(game.board[1], 0); });
test('does not capture when the opposite pit is empty', () => { const game = custom([[2,1],[7,1]]); const result = game.makeMove(2); assert.equal(result.captureOccurred, false); assert.equal(game.board[3], 1); });
test('long sowing can pass the source pit and preserves 72 stones', () => { const game = custom([[0,15],[1,1],[7,1]]); const result = game.makeMove(0); assert.equal(result.success, true); assert.ok(game.board[0] > 0); assert.equal(sum(game.board), 72); });
test('an empty side finishes game, collects remaining stones, and determines p1/p2/draw', () => { let game = custom([[5,1],[7,3]]); game.makeMove(5); assert.equal(game.gameOver, true); assert.equal(game.endReason, 'emptySide'); assert.equal(sum(game.board),72); game = custom([[1,3],[12,1],[6,60],[13,8]],2); game.makeMove(12); assert.equal(game.winner, 1); game = new KalahGame({board:[0,0,1,0,0,0,31,1,0,4,0,0,0,35],currentPlayer:1,startingPlayer:1,firstMoveCompleted:true}); game.makeMove(2); assert.equal(game.winner, 0); });
test('a store score above half is not by itself game over', () => { const game = custom([[0,1],[1,1],[7,1],[6,40]]); const result = game.makeMove(1); assert.equal(result.gameOver, false); });
test('resignation selects the other player rather than comparing stores', () => { let game = new KalahGame(); let r = game.resign(1); assert.equal(r.winner,2); game = new KalahGame(); r = game.resign(2); assert.equal(r.winner,1); });
test('clone is independent and state can serialize and restore', () => { const game = new KalahGame(); const clone = game.clone(); clone.board[0] = 99; assert.equal(game.board[0],6); const restored = KalahGame.fromJSON(game.toJSON()); assert.deepEqual(restored.toJSON(),game.toJSON()); assert.throws(() => KalahGame.fromJSON({ schemaVersion:1, board:[1] })); });
test('opening restriction is scoped to the actual first player and first sowing only', () => { let game = new KalahGame({ openingRestriction:true, startingPlayer:1 }); assert.equal(game.makeMove(0).reason,'OPENING_MOVE_FORBIDDEN'); game.makeMove(1); assert.equal(game.firstMoveCompleted,true); game.currentPlayer=1; assert.equal(game.makeMove(0).success,true); game = new KalahGame({ openingRestriction:true, startingPlayer:2, currentPlayer:2 }); assert.equal(game.makeMove(7).reason,'OPENING_MOVE_FORBIDDEN'); });
